### PR TITLE
add support for local-exec hooks

### PR DESCRIPTION
**Pull request by arewm**

### CODE REVIEW

**Comment by arewm** [comment]
Implements https://github.com/ibm-cloud-architecture/terraform-module-icp-deploy/issues/24

**Review by hassenius — COMMENTED** [review]
Thanks. 
A consideration here may be use cases that would use interpolations, such as automatically configuring local cli clients.
Terraform (at least as of 0.11) really does not like to include interpolations in `count`, but I think if you move the condition in the local-*-hook section from `count` to the `command` statement we'll get an added benefit that the hook can include interpolations. Since it's executing locally, and only once it  shouldn't have much of a penalty to always execute some statement (if needed just a blank echo, for example)
I'm not sure if putting interpolations into `var.hooks["local-*-hooks"]` might throw existing remote hooks into a tailspin, in which case we might consider spinning the local-hooks  into a separate variable.

**Comment by arewm** [comment]
I added default hooks so there is no need for a count check. I think that the best way to perform interpolations will be to use a script that leverages the outputs as I do not know if interpolations in variables will be resolved in the first place.

**Comment by arewm** [comment]
I made one last commit to allow hooks to continue on failure. This will enable the user to restart VM(s) if desired from the hooks. I do not like how it duplicates the code, but put it in for review anyway. 

I can rip it out and put it in another PR after this one if the implementation needs to be hashed out some more, or just keep it out if the functionality is not desired.

**Pull request merged**
